### ISSUE TITLE
tt_reboot doesn't work anymore

### ISSUE THREAD

**Issue by Grimler91** [dlenski/ttblue#10]
tt_reboot currently doesn't work for either watch version. 
How did it work before? Sending lots of zeros causes device to freeze and reboot?

First error is 
```
Rebooting watch...
Expected ATT WRITE response opcode (0x13) but received 0x1b
```
Looking at the bluetooth traffic I can see that this happens because the watch sends both a 0x13 and a 0x1b, i.e. traffic is something like 
```
25 <-- 00 00 00 00 (write req)
25 ->  00 13           (write response)
25 ->  00 00 00 00 (value notification handle (0x1b))
```
And when we flood the device the order is messed up which causes this error:
```
25 <-- 00 00 00 00 (write req)
25 ->  00 13           (write response)
25 <-- 00 00 00 00 (write req)
25 ->  00 00 00 00 (0x1b)
```

I tried fixing this by using write instead of wrreq and to change so that wrreq allows 0x1b as response but I haven't been able to cause a reboot, it doesn't seem to be possible in the same way anymore.

**Comment by Grimler91** [comment]
By allowing 0x1b as a response I mean applying this to bbatt.c:
```
@@ -83,8 +83,8 @@ att_wrreq(int fd, uint16_t handle, const void *buf, int length)
         struct bt_att_pdu_error_rsp *err = (void *)rpkt.buf;
         fprintf(stderr, "ATT error for opcode 0x%02x, handle 0x%04x: %s\n", err->opcode, btohs(err->handle), att_ecode2str(err->ecode));
         return -2;
-    } else if (rpkt.opcode != BT_ATT_OP_WRITE_RSP) {
-        fprintf(stderr, "Expected ATT WRITE response opcode (0x%02x) but received 0x%02x\n", BT_ATT_OP_WRITE_RSP, rpkt.opcode);
+    } else if (rpkt.opcode != BT_ATT_OP_WRITE_RSP && rpkt.opcode != BT_ATT_OP_HANDLE_VAL_NOT) {
+      fprintf(stderr, "Expected ATT WRITE response opcode (0x%02x) or (0x%02x) but received 0x%02x\n", BT_ATT_OP_WRITE_RSP, BT_ATT_OP_HANDLE_VAL_NOT, rpkt.opcode);
         return -2;
     }
 

```

**Comment by dlenski** [comment]
> How did (does) tt_reboot work?

It was an ugly hack. In order to get some of the settings changes to "take", the watch has to reboot. But there is no obvious way to get the watch to reboot via the BLE interface ([via USB there is](https://github.com/ryanbinns/ttwatch/blob/master/src/libttwatch.cpp#L732-L742)).

What I found is that blasting `0` bytes at the read-only status register for a second or two would cause the watch to reboot. This seemed unlikely to harm it or cause any permanent changes to its internal state.

> At least on my tt_reboot currently doesn't work for either watch version.

It was probably only possible due to a timing bug in an earlier firmware version. If there's no better way to trigger a reboot, perhaps it should just be ripped out and replaced with a warning "watch needs to be rebooted in order to update time." :frowning_face:

**Comment by Grimler91** [comment]
Thanks for clarifying. 

> perhaps it should just be ripped out and replaced with a warning "watch needs to be rebooted in order to update time."

Sounds like the most reasonable course of action. 
I wonder what the android app does after utc is updated though, I can check if the bluetooth traffic shows something interesting. 

I'll leave the issue open and close it with a future pull request.

**Comment by dlenski** [comment]
> I wonder what the android app does after utc is updated though, I can check if the bluetooth traffic shows something interesting.

Unfortunately, the official app didn't touch the preferences file at all, last time I checked. So I'm unsure whether they thought to include the necessary reboot command in the firmware :(

**Comment by Grimler91** [comment]
Alright, I had the chance to test a v1 watch a couple of days ago. 

The current v1 implementation didn't work, and neither did the v2 implementation with the 0x07 command.

I'll close this issue as I guess there isn't anything we can do to change this
