### ISSUE TITLE
Requirements for data retrieval via android app? 

### ISSUE THREAD

**Issue by dbrb2** [dlenski/ttblue#3]
This is more a query than an issue....hope you don't mind

I don't use the mysports site, but being able to retrieve the ttbin files is useful. From a desktop I can use ttwatch to extract them over USB and upload to strava, but over bluetooth & android I currently have a problem: 

When I try to retrieve data from my watch via the android app, it complains that it is not linked to a mysports account, and at that point gives up on retrieval of a ttbin file. 

I have checked, and the app comes to this conclusion even in the absence of any internet connection. So my assumption is that it must base this conclusion on the contents (or lack thereof) of the preferences file 0x000f2000 ....

Can you shed any light on this...? I don't suppose you have any plans in the pipeline for a basic "connect, download data, disconnect" android release :-)

**Comment by dlenski** [comment]
> I have checked, and the app comes to this conclusion even in the absence of any internet 
> connection. So my assumption is that it must base this conclusion on the contents (or lack thereof) of 
> the preferences file 0x000f2000 ....

Hi @dbrb2, you are correct. The Android app insists on tying itself to a MySports account, even though there is *absolutely no technical reason* why it should be unable to download the TTBIN files without this account. (`ttblue` is proof of that :+1:)

> I don't suppose you have any plans in the pipeline for a basic "connect, download data, disconnect" android release :-)

I have thought about this. However, I have no experience writing Android apps and Java isn't very high on the list of programming languages that I enjoy using.

I might get around to it eventually, but it should also be possible for someone else who's more familiar with the Android SDK to do so using the protocol documentation I added to [tt_bluetooth.md](https://github.com/dlenski/ttblue/blob/master/tt_bluetooth.md) and the source code. I'd be happy to to help work out any ambiguities in my code and docs!
