### ISSUE TITLE
v2 devices don't work with firmware v1.20

### ISSUE THREAD

**Issue by dlenski** [dlenski/ttblue#5]
@drkingpo's device was working with the `v2_devices` branch and firmware v1.19, but after firmware v1.20 upgrade it hangs at the end of downloading a ~72KiB activity file.

Possible timing issue? Maybe the device is just slow to output the success message after download is completed?

**Comment by wsxarcher** [comment]
What about 1.3.27?

https://en.discussions.tomtom.com/spark-runner-2-473/new-version-1327-spark-and-runner-2-available-1001913

**Comment by dlenski** [comment]
Well, it's only *11 hours old*, and I don't personally own one of the v2 devices, so it's up to you guys to test it and tell me if it works :-p

**Comment by dlenski** [comment]
In order to support one of the newer firmware versions (1.2.0 or 1.3.27), I will probably need new `btsnoop_hci.log` files to understand how the official TomTom Android app.

@drkingpo is a pro at this now :+1:

1. Install the official TomTom app on a phone running Android 4.4 or newer
2. Use Android's Bluetooth capture feature to record all the packets going to the watch
3. Details of how to do this are here: http://www.nowsecure.com/blog/2014/02/07/bluetooth-packet-capture-on-android-4-4/

**Comment by wsxarcher** [comment]
I wish to help but the official app doesn't work on Android 6.0 ...
Maybe I can find an old android phone.

**Comment by drkingpo** [comment]
I think ther is no need to recatch the traffic, as this is a new FW to the watch, not a new Application for Windows, Android or iOS.
>  this is an update to the watch software, not the Connect desktop software. 

More wondering why its not called 1.3.0, but 1.3.27


regards

**Comment by dlenski** [comment]
> I think ther is no need to recatch the traffic, as this is a new FW to the watch, not a new Application for Windows, Android or iOS.

That doesn't matter. The new firmware **could have** changed the communication protocol with the host in some way. There have been many updates to the Android app recently, and they may well be related to supporting whatever has changed in the recent versions of the watch firmware.

> More wondering why its not called 1.3.0, but 1.3.27

Assuming TomTom is using something like [semantic versioning](http://semver.org/), it probably just means that they went through versions 1.3.0-1.3.26 internally and kept finding bugs in them and fixing them, before they decided 1.3.27 was ready for release :-P

**Comment by dlenski** [comment]
I figured out the problem with the new firmware. It was indeed necessary to see the btsnoop logs to understand what had changed. **Thanks again to @drkingpo for providing me with the logs!**

* In all previously-seen versions of the firmware (both for v1 and v2 devices), after successfully reading a file from the watch, it returns a status value of `(uint32_t)0` ([file read protocol for v1 devices](https://github.com/dlenski/ttblue/blob/master/tt_bluetooth.md#read-from-file)).
* But in this new firmware for the v2 devices, a different status value is returned, with the lowest byte zero but the others non-zero.

I don't yet understand what this new status value _means_ (possibly, nothing important :-P) but…
* @drkingpo, can you please test the latest build of `v2_devices` with firmware 1.2.0 and let me know if it works now? (the fix is in aa3c458900e5a3f6c2eba7d5299a77b341d29d26)
* @wsxarcher, if you can test it with 1.3.27 and let me know if that works too, that'd be great

**Comment by dlenski** [comment]
Okay, at least v1.2.0 is working now. Closed!
