### ISSUE TITLE
Does combined version work for v2 devices?

### ISSUE THREAD

**Issue by dlenski** [dlenski/ttblue#6]
I've combined the v1 and v2 device support together. It's working just fine for me on my v1 device, but I'd like to get some feedback as to whether the new version works on v2 devices as well.

Besides heavily reorganizing the code, I made some changes to the scanning procedure which make for more reliable connection with the v1 devices.

Please let me know if the `combined` branch works for anyone with a v2 device!

/cc @drkingpo, @wsxarcher, @mplusband

**Comment by drkingpo** [comment]
Hi Dan,

thanks for your work.

Sorry v2 is crashig directly after connecting.  (Device is recogniced, Pairing code is generated, and seems to connetc, but than closes with:

kingpo@kingpo-Dell-Precision-M3800:~/Downloads/ttblue-master$ ./ttblue -a
****************************************************************
Please put device in pairing mode (MENU -> PHONE -> PAIR NEW)...
****************************************************************
Press Enter to continue: 

Scanning for TomTom BLE devices...
Saw a TomTom device (E4:04:39:53:xx:xx)    
Connected at Tue May 17 08:22:09 2016.
ATT error for opcode 0x0a, handle 0x000b: Invalid handle
Could not read device PPCP (handle 0x000b): Input/output error (5)Fatal error, exiting.
kingpo@kingpo-Dell-Precision-M3800:~/Downloads/ttblue-master$

**Comment by dlenski** [comment]
@drkingpo, I think you are running the **master** branch here, which still only supports the v1 devices.

The correct version is the **`combined`** branch. If you are running the `combined` branch, it will say `Connected to v1 device` or `Connected to v2 device` instead of just `Connected at`.

**Comment by drkingpo** [comment]
yepp, you are right i used the wrong one, now with comined:

kingpo@kingpo-Dell-Precision-M3800:~/Downloads/ttblue-combined$ ./ttblue -a
****************************************************************
Please put device in pairing mode (MENU -> PHONE -> PAIR NEW)...
****************************************************************
Press Enter to continue: 

Scanning for TomTom BLE devices...
Saw a TomTom device (E4:04:39:53:xx:xx)    
Connected to v2 device at Tue May 24 10:47:19 2016.
ATT error for opcode 0x0a, handle 0xffff: Invalid handle
Could not read device PPCP (handle 0xffff): Input/output error (5)Fatal error, exiting.



Finally its nearly the same. Hanle 0xffff now.

**Comment by dlenski** [comment]
Thanks for testing, @drkingpo. That was a dumb mistake by me, fixed now.

I've merged it into the `master` branch, so you can just use the regular `master` branch now... and I'll keep my fingers crossed that I finally have a version which will work with both the v1 and v2 devices.

:8ball:
